[tool.poetry]
name = "bci-dockerfile-generator"
version = "0.1.0"
description = "Generator script for the Dockerfiles for the SLE BCI"
authors = ["Dan Čermák <dcermak@suse.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = ">=3.6.2,<4.0"
Jinja2 = "^3.0"
dataclasses = { version = ">=0.8", markers="python_version < '3.7'" } 

[tool.poetry.dev-dependencies]
black = "^21.12b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
