---
name: Update the deployment branches containing the build recipes

on:
  push:
    branches:
      - main

jobs:
  create-pull-requests:
    name: create pull requests if the build recipes changed
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        os_version:
          - 4
          - 3
          - Tumbleweed

    steps:
      # we need all branches for the build checks
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: Gr1N/setup-poetry@v7
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: poetry-${{ hashFiles('poetry.lock') }}

      - run: |
          . /etc/os-release
          echo "deb http://download.opensuse.org/repositories/openSUSE:/Tools/xUbuntu_$VERSION_ID/ /" | sudo tee /etc/apt/sources.list.d/openSUSE:Tools.list
          curl -fsSL https://download.opensuse.org/repositories/openSUSE:Tools/xUbuntu_$VERSION_ID/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/openSUSE_Tools.gpg > /dev/null
          sudo apt update
          sudo apt install osc fish

      - name: install python dependencies
        run: poetry install

      - name: setup the continuous rebuild project
        run: poetry run ./scratch-build-bot.py --os-version ${{ matrix.os_version }} create_cr_project
        env:
          OSC_PASSWORD: ${{ secrets.OSC_PASSWORD }}
          OSC_USER: "defolos"

      - name: configure git user
        run: |
          git config user.name "SUSE Update Bot"
          git config user.email "noreply@suse.com"

      - name: commit the changes to a test branch
        run: |
          set -eux pipefail
          poetry run ./scratch-build-bot.py \
              --os-version ${{ matrix.os_version }} \
              -vvvv \
              --branch-name "for-deploy-${{ matrix.os_version }}" \
              commit_state \
              --commit-message "🤖: Update build recipes from templates" \
            | tee commit_state_out
          if [[ "$(wc -l commit_state_out | awk '{print $1}')" = "1" ]]; then
              echo "DEPLOYMENT_COMMIT_HASH=$(cat commit_state_out)" >> $GITHUB_ENV
          else
              echo "no_change=true" >> $GITHUB_ENV
          fi
          cat test-build.env >> $GITHUB_ENV
        env:
          OSC_USER: "defolos"

      - name: create a pull request
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_FROM_BRANCH: ${{ env.BRANCH_NAME }}
          PULL_REQUEST_BRANCH: ${{ env.DEPLOYMENT_BRANCH_NAME }}
          PULL_REQUEST_TITLE: "🤖: Update build recipes for ${{ env.OS_VERSION_PRETTY }}"
          PULL_REQUEST_UPDATE: 1
        if: env.no_change != 'true'
